-- SQL Script to fix all @Lob String columns from oid to TEXT type
-- Run this script on your PostgreSQL database to fix existing columns

-- Admin Management Services Schema
ALTER TABLE IF EXISTS "admin"."HMS_TM_CHARGES" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_CHARGES" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_CHARGE_CATEGORY" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_CHARGE_CATEGORY" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_SOURCE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_SOURCE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_PURPOSE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_PURPOSE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_ROLE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_ROLE" ALTER COLUMN "SCOPE_IDS" TYPE TEXT USING "SCOPE_IDS"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_COMPLAINT_TYPE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_COMPLAINT_TYPE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_EMPLOYEE" ALTER COLUMN "PHOTO" TYPE TEXT USING "PHOTO"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_EMPLOYEE" ALTER COLUMN "RESUME" TYPE TEXT USING "RESUME"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_EMPLOYEE" ALTER COLUMN "JOINING_LETTER" TYPE TEXT USING "JOINING_LETTER"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_EMPLOYEE" ALTER COLUMN "RESIGNATION_LETTER" TYPE TEXT USING "RESIGNATION_LETTER"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_EMPLOYEE" ALTER COLUMN "OTHER_DOCUMENTS" TYPE TEXT USING "OTHER_DOCUMENTS"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_EMPLOYEE" ALTER COLUMN "PHOTO" TYPE TEXT USING "PHOTO"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_EMPLOYEE" ALTER COLUMN "CURRENT_ADDRESS" TYPE TEXT USING "CURRENT_ADDRESS"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_EMPLOYEE" ALTER COLUMN "PERMANENT_ADDRESS" TYPE TEXT USING "PERMANENT_ADDRESS"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_EMPLOYEE" ALTER COLUMN "RESUME" TYPE TEXT USING "RESUME"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_EMPLOYEE" ALTER COLUMN "JOINING_LETTER" TYPE TEXT USING "JOINING_LETTER"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_EMPLOYEE" ALTER COLUMN "RESIGNATION_LETTER" TYPE TEXT USING "RESIGNATION_LETTER"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_EMPLOYEE" ALTER COLUMN "OTHER_DOCUMENTS" TYPE TEXT USING "OTHER_DOCUMENTS"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_PATIENT_ID_CARD" ALTER COLUMN "BARCODE_OR_QR_CODE" TYPE TEXT USING "BARCODE_OR_QR_CODE"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_PATIENT_ID_CARD" ALTER COLUMN "BACKGROUND_IMAGE" TYPE TEXT USING "BACKGROUND_IMAGE"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_PATIENT_ID_CARD" ALTER COLUMN "LOGO_IMAGE" TYPE TEXT USING "LOGO_IMAGE"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_PATIENT_ID_CARD" ALTER COLUMN "SIGNATURE_IMAGE" TYPE TEXT USING "SIGNATURE_IMAGE"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_PAYROLL" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TM_TIMELINE" ALTER COLUMN "DOCUMENT" TYPE TEXT USING "DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "admin"."HMS_TW_NOTICE_ANNOUNCEMENT" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;

-- IPD Management Services Schema
ALTER TABLE IF EXISTS "ipd"."HMS_TM_ANTENATAL_FINDING" ALTER COLUMN "ANTENATAL_EXAMINATION" TYPE TEXT USING "ANTENATAL_EXAMINATION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_ANTENATAL_FINDING" ALTER COLUMN "CONDITION" TYPE TEXT USING "CONDITION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_ANTENATAL_FINDING" ALTER COLUMN "PELVIC_EXAMINATION" TYPE TEXT USING "PELVIC_EXAMINATION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_ANTENATAL_FINDING" ALTER COLUMN "SPECIAL_FINDINGS_REMARK" TYPE TEXT USING "SPECIAL_FINDINGS_REMARK"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_ANTENATAL_FINDING" ALTER COLUMN "REMARK" TYPE TEXT USING "REMARK"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_ANTENATAL_FINDING" ALTER COLUMN "PREVIOUS_ANTENATAL_DETAILS" TYPE TEXT USING "PREVIOUS_ANTENATAL_DETAILS"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_POSTNATAL_HISTORY" ALTER COLUMN "ROUTINE_QUESTION" TYPE TEXT USING "ROUTINE_QUESTION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_POSTNATAL_HISTORY" ALTER COLUMN "GENERAL_REMARK" TYPE TEXT USING "GENERAL_REMARK"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_CONSULTANT_REGISTER" ALTER COLUMN "INSTRUCTION" TYPE TEXT USING "INSTRUCTION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PREVIOUS_OBSTETRIC_HISTORY" ALTER COLUMN "PREVIOUS_MEDICAL_HISTORY" TYPE TEXT USING "PREVIOUS_MEDICAL_HISTORY"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PREVIOUS_OBSTETRIC_HISTORY" ALTER COLUMN "SPECIAL_INSTRUCTION" TYPE TEXT USING "SPECIAL_INSTRUCTION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPD_CHARGES" ALTER COLUMN "CHARGE_NOTE" TYPE TEXT USING "CHARGE_NOTE"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPDOPERATION" ALTER COLUMN "OPERATION_CATEGORY" TYPE TEXT USING "OPERATION_CATEGORY"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPDOPERATION" ALTER COLUMN "OPERATION_NAME" TYPE TEXT USING "OPERATION_NAME"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPDPAYMENTS" ALTER COLUMN "CHEQUE_ATTACHMENT" TYPE TEXT USING "CHEQUE_ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPDPAYMENTS" ALTER COLUMN "NOTE" TYPE TEXT USING "NOTE"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPDDOSAGE" ALTER COLUMN "REMARKS" TYPE TEXT USING "REMARKS"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPDADMISSIONS" ALTER COLUMN "DISCHARGE_SUMMARY" TYPE TEXT USING "DISCHARGE_SUMMARY"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_IPDADMISSIONS" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PRESCRIPTIONS" ALTER COLUMN "FINDING_DESCRIPTION" TYPE TEXT USING "FINDING_DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PRESCRIPTIONS" ALTER COLUMN "HEADER_NOTE" TYPE TEXT USING "HEADER_NOTE"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PRESCRIPTIONS" ALTER COLUMN "FOOTER_NOTE" TYPE TEXT USING "FOOTER_NOTE"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PRESCRIPTIONS" ALTER COLUMN "REPORT_NAME" TYPE TEXT USING "REPORT_NAME"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PRESCRIPTIONS" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_PRESCRIPTIONDETAILS" ALTER COLUMN "INSTRUCTION" TYPE TEXT USING "INSTRUCTION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_TIMELINE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "ipd"."HMS_TM_TIMELINE" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;

-- OPD Management Services Schema  
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPD_CHARGES" ALTER COLUMN "CHARGE_NOTE" TYPE TEXT USING "CHARGE_NOTE"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDOPERATION" ALTER COLUMN "OPERATION_CATEGORY" TYPE TEXT USING "OPERATION_CATEGORY"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDOPERATION" ALTER COLUMN "OPERATION_NAME" TYPE TEXT USING "OPERATION_NAME"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDPAYMENTS" ALTER COLUMN "CHEQUE_ATTACHMENT" TYPE TEXT USING "CHEQUE_ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDPAYMENTS" ALTER COLUMN "NOTE" TYPE TEXT USING "NOTE"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDDOSAGE" ALTER COLUMN "REMARKS" TYPE TEXT USING "REMARKS"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDADMISSIONS" ALTER COLUMN "DISCHARGE_SUMMARY" TYPE TEXT USING "DISCHARGE_SUMMARY"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDADMISSIONS" ALTER COLUMN "REPORT" TYPE TEXT USING "REPORT"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDADMISSIONS" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDPRESCRIPTIONS" ALTER COLUMN "FINDING_DESCRIPTION" TYPE TEXT USING "FINDING_DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDPRESCRIPTIONS" ALTER COLUMN "REPORT_NAME" TYPE TEXT USING "REPORT_NAME"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDPRESCRIPTIONS" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDTIMELINE" ALTER COLUMN "DESCRIPTION" TYPE TEXT USING "DESCRIPTION"::TEXT;
ALTER TABLE IF EXISTS "opd"."HMS_TM_OPDTIMELINE" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;

-- Billing Management Services (no schema prefix, uses default)
ALTER TABLE IF EXISTS "HMS_TM_PATHOLOGY_TEST" ALTER COLUMN "UPLOAD_REPORT" TYPE TEXT USING "UPLOAD_REPORT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_RADIOLOGY_TEST" ALTER COLUMN "UPLOAD_REPORT" TYPE TEXT USING "UPLOAD_REPORT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_PATHOLOGY_BILL" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_RADIOLOGY_BILL" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_PHARMACY_BILL" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_PURCHASE_BILL" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_PURCHASE_BILL" ALTER COLUMN "CHEQUE_ATTACH_DOCUMENT" TYPE TEXT USING "CHEQUE_ATTACH_DOCUMENT"::TEXT;

-- Finance Management Services
ALTER TABLE IF EXISTS "HMS_TM_INCOME_RECORD" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_EXPENSE" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;

-- Inventory Management Services
ALTER TABLE IF EXISTS "HMS_TM_ITEM_STOCK" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;

-- Patient Management Services
ALTER TABLE IF EXISTS "patient"."HMS_TM_PATIENTS" ALTER COLUMN "OLD_PRESCRIPTION" TYPE TEXT USING "OLD_PRESCRIPTION"::TEXT;

-- Birth/Death Management Services
ALTER TABLE IF EXISTS "birth_death"."HMS_TM_BIRTH_RECORD" ALTER COLUMN "MOTHER_PHOTO" TYPE TEXT USING "MOTHER_PHOTO"::TEXT;
ALTER TABLE IF EXISTS "birth_death"."HMS_TM_BIRTH_RECORD" ALTER COLUMN "FATHER_PHOTO" TYPE TEXT USING "FATHER_PHOTO"::TEXT;
ALTER TABLE IF EXISTS "birth_death"."HMS_TM_BIRTH_RECORD" ALTER COLUMN "CHILD_PHOTO" TYPE TEXT USING "CHILD_PHOTO"::TEXT;
ALTER TABLE IF EXISTS "birth_death"."HMS_TM_BIRTH_RECORD" ALTER COLUMN "DOCUMENT_PHOTO" TYPE TEXT USING "DOCUMENT_PHOTO"::TEXT;
ALTER TABLE IF EXISTS "birth_death"."HMS_TM_DEATH_RECORD" ALTER COLUMN "ATTACHMENT" TYPE TEXT USING "ATTACHMENT"::TEXT;

-- Bloodbank Management Services
ALTER TABLE IF EXISTS "HMS_TM_ISSUE_COMPONENT" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_ISSUE_BLOOD" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_BLOOD_DONOR_DETAILS" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_BAG_STOCK" ALTER COLUMN "ATTACH_DOCUMENT" TYPE TEXT USING "ATTACH_DOCUMENT"::TEXT;

-- TPA Management Services
ALTER TABLE IF EXISTS "tpa"."HMS_TM_TPA_DETAILS" ALTER COLUMN "OTHER_DOCUMENTS" TYPE TEXT USING "OTHER_DOCUMENTS"::TEXT;

-- Ambulance Management Services
ALTER TABLE IF EXISTS "HMS_TM_ADDVEHICLE" ALTER COLUMN "NOTE" TYPE TEXT USING "NOTE"::TEXT;
ALTER TABLE IF EXISTS "HMS_TM_ADDAMBULANCECALL" ALTER COLUMN "NOTE" TYPE TEXT USING "NOTE"::TEXT;

