import React, { useState } from "react"
import { Button, Col, Form, FormGroup, Input, Label, Row } from "reactstrap"
import { paymentModeData } from "../../common/data/FakeData";
import BillTransaction from "../Billing/BillSummary/BillTransaction";
import TransactionHistoryDataTable from "./TransactionHistoryDataTable";

const AddPayments = (props: any) => {
    const [date, setDate] = useState('');
    const [amount, setAmount] = useState('');
    const [paymentMode, setPaymentMode] = useState('');
    const [note, setNote] = useState('');
    const [chequeNo, setChequeNo] = useState('');
    const [chequeDate, setChequeDate] = useState('');

    const handleDateChange = (value: any) => {
        setDate(value);
    }

    const handleAmountChange = (value: any) => {
        setAmount(value);
    }

    return (
        <React.Fragment>
            <Row>
                <Col md={8}>
                    <table className="noBorderTable">
                        <tbody>
                            <tr>
                                <th>Bill No</th>
                                <td>PHARMAB410</td>
                                <th className="text-end">Total (₹)</th>
                                <td className="text-end">300.00</td>
                            </tr>
                            <tr>
                                <th>Case ID</th>
                                <td>6721</td>
                                <th className="text-end">Discount Percentage (₹)</th>
                                <td className="text-end">(10.00%) 30.00</td>
                            </tr>
                            <tr>
                                <th>Patient</th>
                                <td>Hayley Matthews (1121)</td>
                                <th className="text-end">Tax (₹)</th>
                                <td className="text-end">13.50</td>
                            </tr>
                            <tr>
                                {/* <th>Generated By</th>
                                <td>Super Admin (9001)</td> */}
                                <th className="text-end">Net Amount (₹)</th>
                                <td className="text-end">283.50</td>
                            </tr>
                            <tr>
                                <th>Date</th>
                                <td>10/16/2024 04:20 PM</td>
                                <th className="text-end">Paid Amount (₹)</th>
                                <td className="text-end">283.50</td>
                            </tr>
                            <tr>
                                <th>Mobile</th>
                                <td>7809078654</td>
                                <th className="text-end">Refund Amount (₹)</th>
                                <td className="text-end">0.00</td>
                            </tr>
                            <tr>
                                <th></th>
                                <td></td>
                                <th className="text-end">Due Amount (₹)</th>
                                <td className="text-end">0.00</td>
                            </tr>
                        </tbody>
                    </table>
                </Col>
                <Col md={4}>
                    <Form>
                        <FormGroup>
                            <label className="text-start mb-2">Date <span className="text-danger">*</span></label>
                            <Input
                                id="date"
                                name="date"
                                type="datetime-local"
                                value={date}
                                onChange={e => handleDateChange(e.target.value)}
                            />
                        </FormGroup>
                        <FormGroup>
                            <label className="text-start mb-2">Amount  (₹)<span className="text-danger">*</span></label>
                            <Input
                                id="amount"
                                name="amount"
                                type="text"
                                value={amount}
                                onChange={e => handleAmountChange(e.target.value)}
                            />
                        </FormGroup>
                        <Col>
                            <FormGroup>
                                <label className="text-start mb-2">Payment Mode</label>
                                <select
                                    className={`form-control`}
                                    value={paymentMode} onChange={(e) => { setPaymentMode(e.target.value) }}
                                >
                                    <option value="">--Select Payment Mode--</option>
                                    {paymentModeData.map((data: any, idx: any) => (
                                        <option key={idx} value={data.type}>{data.type}</option>
                                    ))}
                                </select>
                            </FormGroup>
                        </Col>
                        {paymentMode === "Cheque" && (
                            <Row>
                                <Col md={6}>
                                    <FormGroup>
                                        <label className="text-start mb-2">Cheque No<span className="text-danger">*</span></label>
                                        <Input
                                            id="ChequeNo"
                                            name="ChequeNo"
                                            type="text"
                                            value={chequeNo}
                                            onChange={e => setChequeNo(e.target.value)}
                                        />
                                    </FormGroup>
                                </Col>
                                <Col>
                                    <FormGroup>
                                        <label className="text-start mb-2">Cheque Date<span className="text-danger">*</span></label>
                                        <Input
                                            id="ChequeDate"
                                            name="ChequeDate"
                                            type="date"
                                            value={chequeDate}
                                            onChange={e => setChequeDate(e.target.value)}
                                        />
                                    </FormGroup>
                                </Col>
                                <Col>
                                    <FormGroup>
                                        <label className="text-start mb-2">Attach Document</label>
                                        <Input
                                            type="file"
                                            className="form-control"
                                            id="AttachDocument"
                                        />
                                    </FormGroup>
                                </Col>
                            </Row>
                        )}
                        <FormGroup>
                            <label className="text-start mb-2">Note</label>
                            <textarea className="form-control"
                                id="note"
                                name="note"
                                value={note}
                                onChange={e => setNote(e.target.value)}
                            />
                        </FormGroup>

                        <Col className="text-end my-3">
                            <Button color="primary">Save</Button>
                        </Col>
                    </Form>

                </Col>
            </Row>
            <Row>
                <TransactionHistoryDataTable />
            </Row>
        </React.Fragment>
    )
}

export default AddPayments