import React, { useEffect, useState } from "react"
import { Container, Row, Col, Label } from "reactstrap"
import TransactionHistoryDataTable from "../Pharmacy/TransactionHistoryDataTable"
import BloodBankApiService from "../../helpers/services/bloodBank/BloodBankApiService";
import moment from "moment";

const PreviewBloodIssueDetails = (props: any) => {
    const bloodBankApiService: BloodBankApiService = new BloodBankApiService();

    const [bloodIssueData, setBloodIssueData] = useState<any>();

    const getAllComponentIssue = async () => {
        try {
            let id = props.data.issueBloodId
            let result = await bloodBankApiService.getAllIssueBlood(id);
            console.log("getAllComponentIssue", result);
            setBloodIssueData(result);
        } catch (error: any) {
            console.log("getAllComponentIssue Error");
            console.log(error);
        }
    }

    useEffect(() => {
        getAllComponentIssue();
    }, []);

    return (
        <React.Fragment>
            <Container fluid>
                <Row>
                    <Col className="justify-content-between d-flex">
                        <Label> Bill No : {bloodIssueData?.issueBloodId}</Label>
                        <Label>Issue Date : {moment(bloodIssueData?.issueDate).format('DD/MM/YYYY hh:mm A')}</Label>
                    </Col>
                </Row>
                <hr />
                <Row>
                    <Col>
                        <Row>
                            <Col><Label>IPD/OPD ID</Label></Col>
                            <Col><Label>: {bloodIssueData?.ipdOrOpdId || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>Received To	</Label></Col>
                            <Col><Label>: {bloodIssueData?.patientDetails?.firstName} {bloodIssueData?.patientDetails?.lastName} ({bloodIssueData?.patientId})</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>Bags</Label></Col>
                            <Col>
                                <Label>: {bloodIssueData?.bagStocks
                                    ? `${bloodIssueData.bagStocks.bagNo} (${bloodIssueData.bagStocks.volume} ${bloodIssueData.bagStocks.unitType})`
                                    : 'NA'}
                                </Label>
                            </Col>
                        </Row>
                        <Row>
                            <Col><Label>Blood Group	</Label></Col>
                            <Col><Label>: {bloodIssueData?.bloodGroup || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>Reference</Label></Col>
                            <Col><Label>: {bloodIssueData?.referenceName || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>Note</Label></Col>
                            <Col><Label>: {bloodIssueData?.note || 'NA'}</Label></Col>
                        </Row>
                    </Col>
                    <Col>

                        <Row>
                            <Col><Label>Donor Name	</Label></Col>
                            <Col><Label>: {bloodIssueData?.donorName || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>Technician</Label></Col>
                            <Col><Label>: {bloodIssueData?.technician || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>TPA</Label></Col>
                            <Col><Label>: {bloodIssueData?.tpa || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>TPA ID	</Label></Col>
                            <Col><Label>: {bloodIssueData?.tpaId || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>TPA Validity</Label></Col>
                            <Col><Label>: {bloodIssueData?.tpaValidity || 'NA'}</Label></Col>
                        </Row>
                        <Row>
                            <Col><Label>Blood Qty</Label></Col>
                            <Col><Label>: {bloodIssueData?.bloodQty || 'NA'}</Label></Col>
                        </Row>
                    </Col>
                </Row>
                <hr />
                <Row className="my-2">
                    {/* <Col>
                        <Label>Generated By	: Super Admin (9001)</Label>
                    </Col> */}
                    <Col md={4}>
                        <Col className="d-flex justify-content-between">
                            <Label>Amount (₹) </Label>
                            <Label>{bloodIssueData?.total}</Label>
                        </Col>
                        <Col className="d-flex justify-content-between">
                            <Label>Discount</Label>
                            <Label>{bloodIssueData?.discount}</Label>
                        </Col>
                        <Col className="d-flex justify-content-between">
                            <Label>Tax </Label>
                            <Label>{bloodIssueData?.tax}</Label>
                        </Col>
                        <Col className="d-flex justify-content-between">
                            <Label>Net Amount (₹) </Label>
                            <Label>{bloodIssueData?.netAmount}</Label>
                        </Col>
                        <Col className="d-flex justify-content-between">
                            <Label>Paid Amount  (₹)  </Label>
                            <Label>{bloodIssueData?.paymentAmount}</Label>
                        </Col>

                        <Col className="d-flex justify-content-between">
                            <Label>Balance Amount (₹)  </Label>
                            <Label>{bloodIssueData?.balanceAmount}</Label>
                        </Col>
                    </Col>
                </Row>
            </Container>
        </React.Fragment>
    )
}

export default PreviewBloodIssueDetails