spring.application.name=hms-discovery-service
spring.cloud.config.label=main
#spring.config.import=optional:configserver:http://localhost:8080/configServer-0.0.1-SNAPSHOT
#spring.config.import=optional:configserver:https://localhost:8888/config-server
#cors.url=${CORS_URL:*}

server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

server.servlet.context-path=/eureka-discovery
eureka.instance.hostname=localhost


####keyConfiguration
#server.ssl.key-store=classpath:hms-eureka-server-key.p12
#server.ssl.key-store-password=hms
#server.ssl.key-password=hms
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=hms-eureka-server-key
###TrustStore
#server.ssl.trust-store=classpath:hms-truststore.p12
#server.ssl.trust-store-password=hms

##keyConfiguration
#server.ssl.key-store=classpath:hms-discovery-keystore.p12
#server.ssl.key-store-password=hms
#server.ssl.key-alias=hms-discovery-key
#server.ssl.key-store-type=PKCS12
###TrustStore
#client.ssl.trust-store=classpath:hms-truststore.p12
#client.ssl.trust-store-password=hms