import { useState } from "react";
import { Button, Col, Modal, ModalBody, ModalHeader, Table } from "reactstrap"
import EditPresciption from "./EditPrescription";
import PreviewPrescription from "./PreviewPrescription";
import IPDApiService from "../../../../../helpers/services/ipd/ipd-api-service";
import { toast } from "react-toastify";
import ErrorHandler from "../../../../../helpers/ErrorHandler";
import DeleteModal from "../../../../../Components/Common/DeleteModal";
import { Link } from "react-router-dom";
import OPDApiService from "../../../../../helpers/services/opd/opd-api-service";
import RoleBasedComponent from "../../../../../common/RolePermission/RoleBasedComponent";

const PrescriptionDataTable = (props: any) => {
    const iPDApiService: IPDApiService = new IPDApiService();
    const opdApiService: OPDApiService = new OPDApiService();

    const [openAddModal, setOpenAddModal] = useState<boolean>(false);
    const [previewModelOpen, setPreviewModelOpen] = useState<boolean>(false);
    const [previewData, setPreviewData] = useState('');
    const [prescriptionId, setPrescriptionId] = useState('');

    //delete 
    const [deleteModal, setDeleteModal] = useState<boolean>(false);
    const [selectedId, setSelectedId] = useState('');

    const edit = (id: any) => {
        setPrescriptionId(id);
        handleClose();
    }
    const handleClose = () => {
        setOpenAddModal(!openAddModal);
    }

    const handlePreviewClose = () => {
        setPreviewModelOpen(!previewModelOpen)
    }

    const preview = (data: any) => {
        setPreviewData(data);
        handlePreviewClose();
    }

    // Delete Data
    const handleDelete = async () => {
        if (selectedId) {
            try {
                if (props.title === 'ipd') {
                    await iPDApiService.deletePrescription(selectedId);
                } else {
                    await opdApiService.deletePrescription(selectedId);
                }
                toast.success('Prescription Deleted Successfully', { containerId: 'TR' });
                setDeleteModal(false);
                props.refresh();
                return;
            } catch (error: any) {
                console.log("handleDelete Error")
                return ErrorHandler(error)
            }
        }
    };

    const deletePrescription = (id: any) => {
        setSelectedId(id);
        setDeleteModal(true);
    }

    return <>
        <Col>
            <div className="table-responsive">
                <Table hover className="table-centered align-middle table-nowrap mb-0">
                    <thead className="table-light">
                        <tr>
                            <th>Prescription No	</th>
                            <th>Date</th>
                            <th>Prescribe By</th>
                            {/* <th>Generated By</th> */}
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {props?.data?.prescriptions && props?.data?.prescriptions?.length > 0 ? (
                            props?.data?.prescriptions?.map((item: any, idx: any) => (
                                <tr key={idx}>
                                    <td className="text-primary">
                                        {item.prescriptionNo}
                                    </td>
                                    <td>{item.datePrescribed}</td>
                                    <td>{item.doctor?.firstName} {item.doctor?.lastName} ({item.doctor?.staffId})</td>
                                    {/* <td>{item.generatedBy || 'Admin'}</td> */}
                                    <td>
                                        <span>
                                            <Link to="#" data-bs-toggle="modal" onClick={() => preview(item.prescriptionId)}
                                                className="btn btn-sm btn-soft-warning edit-list mx-1" title="View">
                                                <i className="ri-eye-line"></i>
                                            </Link>
                                            <RoleBasedComponent allowedRoles={["SUPERADMIN","DOCTOR"]}>
                                                <>
                                                    <Link to="#" data-bs-toggle="modal" onClick={() => edit(item.prescriptionId)}
                                                        className="btn btn-sm btn-soft-info edit-list mx-1" title="Edit">
                                                        <i className="ri-pencil-line"></i>
                                                    </Link>
                                                    <Link to="#" title="Delete" data-bs-toggle="modal" onClick={() => deletePrescription(item.prescriptionId)}
                                                        className="btn btn-sm btn-soft-danger remove-list mx-1">
                                                        <i className="ri-delete-bin-5-line"></i>
                                                    </Link>
                                                </>
                                            </RoleBasedComponent>
                                        </span>
                                    </td>
                                </tr>
                            ))
                        ) : (
                            <tr>
                                <td colSpan={4} className="text-center text-muted">No prescriptions available</td>
                            </tr>
                        )}
                    </tbody>
                </Table>
            </div>
        </Col>

        <Modal isOpen={previewModelOpen} toggle={handlePreviewClose}
            backdrop={'static'} id="staticBackdrop" centered size="xl" scrollable
        >
            <ModalHeader toggle={handlePreviewClose} className="p-3 bg-info-subtle modal-title">
                Prescription
            </ModalHeader>

            <ModalBody>
                <PreviewPrescription title={props.title} id={previewData} data={props.data} handleClose={handlePreviewClose} />
            </ModalBody>
        </Modal>

        <Modal isOpen={openAddModal} toggle={handleClose}
            backdrop={'static'} id="staticBackdrop" centered fullscreen scrollable
        >
            <ModalHeader toggle={handleClose} className="p-3 bg-info-subtle modal-title">
                Edit Presciption
            </ModalHeader>

            <ModalBody>
                <EditPresciption title={props.title} refresh={props.refresh} id={prescriptionId} handleClose={handleClose} />
            </ModalBody>
        </Modal>

        <DeleteModal
            show={deleteModal}
            onDeleteClick={handleDelete}
            onCloseClick={() => setDeleteModal(false)}
        />
    </>
}
export default PrescriptionDataTable