import { faPrint } from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { Button, Col, Container, Label, Row, Table } from "reactstrap"
import PrintComponent from "../../../../../Components/Common/PrintComponent";
import { useEffect, useState } from "react";
import IPDApiService from "../../../../../helpers/services/ipd/ipd-api-service";
import OPDApiService from "../../../../../helpers/services/opd/opd-api-service";
import CalculateAge from "../../../../../Components/Common/CalculateAge";

const PreviewPrescription = (props: any) => {
    const ipdApiService: IPDApiService = new IPDApiService();
    const opdApiService: OPDApiService = new OPDApiService();

    const [data, setData] = useState<any>(props.data);
    const [prescriptionData, setPrescriptionData] = useState<any>('');

    const getPrescriptionById = async () => {
        try {
            if (props.title === 'ipd') {
                let result = await ipdApiService.getPrescriptionById(props.id);
                setPrescriptionData(result);
            } else {
                let result = await opdApiService.getPrescriptionById(props.id);
                setPrescriptionData(result);
            }
        } catch (error: any) {
            console.log("getPrescriptionById Error");
            console.log(error);
        }
    }

    useEffect(() => {
        getPrescriptionById();
    }, []);

    useEffect(() => {
        setData(props.data);
    }, [props.data]);

    return <>
        <Container fluid>
            <Row className="text-end py-3">
                <Col>
                    <PrintComponent contentId="prescriptionContent" />
                </Col>
            </Row>
        </Container>
        <Container fluid id="prescriptionContent">
            <Row>
                <Col className="d-flex align-items-center justify-content-between">
                    <Label>Prescription: {prescriptionData.prescriptionNo}</Label>
                    <Label>Date : {prescriptionData.datePrescribed}</Label>
                </Col>
            </Row>
            <hr />
            <Row>
                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold"> Name</label></Col>
                        <Col xs={8}>{data?.patient?.firstName} {data?.patient?.lastName} ({data?.patient?.patientId})</Col>
                    </Row>
                </Col>
                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Gender</label></Col>
                        <Col xs={8}>{data?.patient?.gender}</Col>
                    </Row>
                </Col>
                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Age</label></Col>
                        <Col xs={8}><CalculateAge dateOfBirth={data?.patient?.dateOfBirth} /></Col>
                    </Row>
                </Col>
                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Blood Group</label></Col>
                        <Col xs={8}>{data?.patient?.bloodType || 'NA'}</Col>
                    </Row>
                </Col>
                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Phone</label></Col>
                        <Col xs={8}>{data?.patient?.contactNumber || 'NA'}</Col>
                    </Row>
                </Col>
                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Prescribe By	</label></Col>
                        <Col xs={8}>{prescriptionData.doctor?.firstName} {prescriptionData.doctor?.lastName} ({prescriptionData.doctor?.staffId})</Col>
                    </Row>
                </Col>
                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Email</label> </Col>
                        <Col xs={8}>{data?.patient?.email || 'NA'}</Col>
                    </Row>
                </Col>
                {/* <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Consultant Doctor </label></Col>
                        <Col xs={8}>{data.admissions?.doctor?.firstName} {data.admissions?.doctor?.lastName} ({data.admissions?.doctor?.staffId})</Col>
                    </Row>
                </Col>

                <Col xs={6}>
                    <Row>
                        <Col xs={4}><label className="fw-bold">Generated By	</label></Col>
                        <Col xs={8}>{prescriptionData.createdBy}</Col>
                    </Row>
                </Col> */}
            </Row>
            <hr />
            <Row>
                <Col xs={6}>
                    <h5>Symptoms</h5>
                    <label>{data.admissions?.symptomsTitle}</label><br />
                    <span>{data.admissions?.symptomsDescription}</span>
                </Col>
                <Col xs={6}>
                    <h5>Finding</h5>
                    <label>{prescriptionData.finding}</label><br />
                    <span>{prescriptionData.findingDescription}</span>
                </Col>
            </Row>
            <hr />
            <Row>
                <Col>
                    <h4>Medicines</h4>
                    <div className="table-responsive">
                        <Table hover className="table-centered align-middle mb-0">
                            <thead className="table-light">
                                <tr>
                                    <th>#	</th>
                                    <th>Medicine Category</th>
                                    <th>Medicine</th>
                                    <th>Dosage</th>
                                    <th>Dose Interval</th>
                                    <th>Dose Duration</th>
                                    <th>Instruction</th>
                                </tr>
                            </thead>
                            <tbody>
                                {prescriptionData?.prescriptionDetails?.map((item: any, idx: any) => (
                                    <tr key={idx}>
                                        <td>{idx + 1}</td>
                                        <td>
                                            {item.medicineCategory}
                                        </td>
                                        <td>{item.medicineName}	</td>
                                        <td>{item.dosage}</td>
                                        <td>{item.dosageInterval}</td>
                                        <td>{item.dosageDuration}</td>
                                        <td>{item.instruction}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </Table>
                    </div>
                </Col>
            </Row>
            <hr />
            <Row>
                {prescriptionData?.pathologyTestDetails?.length > 0 && (
                    <Col xs={6}>
                        <h6>Pathology Test</h6>
                        <ol>
                            {prescriptionData?.pathologyTestDetails?.map((item: any, idx: any) => (
                                <li key={idx}> {item.testName}</li>
                            ))}
                        </ol>
                    </Col>
                )}

                {prescriptionData?.radiologyTestDetails?.length > 0 && (
                    <Col xs={6}>
                        <h6>Radiology Test</h6>
                        <ol>
                            {prescriptionData?.radiologyTestDetails?.map((item: any, idx: any) => (
                                <li key={idx}> {item.testName}</li>
                            ))}
                        </ol>
                    </Col>
                )}
            </Row>
        </Container>
    </>
}
export default PreviewPrescription