import moment from "moment";
import React from "react";
import { Row, Col, Card, Table, CardBody } from "reactstrap";

const PaymentDetails = (props: any) => {
    const data = props.data;

    return (
        <Row>
            <Col lg={6} >

                    <div className="card-body pt-0">
                    <Table className="noBorderTable">
                            <tbody>
                                <tr>
                                    <td>Bill No</td>
                                    <td className="text-primary">{data.billId}</td>
                                </tr>
                                <tr>
                                    <td>IPD Or OPD ID</td>
                                    <td>{data.ipdOrOpdId || 'NA'}</td>
                                </tr>
                                <tr>
                                    <td>Patient</td>
                                    <td className="text-primary">{data.patientDetails?.firstName} {data.patientDetails?.lastName} ({data.patientId})</td>
                                </tr>
                                {/* <tr>
                                    <td>Generated By</td>
                                    <td>Super Admin (9001)</td>
                                </tr> */}
                                <tr>
                                    <td>Date</td>
                                    <td>{moment(data.dateTime).format('DD-MM-YYYY  h:ss A')}</td>
                                </tr>
                                <tr>
                                    <td>Mobile</td>
                                    <td className="text-primary">{data.patientDetails?.contactNumber || 'NA'}</td>
                                </tr>
                            </tbody>
                        </Table>
                    </div>
              
            </Col>
            <Col lg={6} >

                    <div className="card-body pt-0">
                        <Table className="noBorderTable">
                            <tbody>
                                <tr>
                                    <td>Total (₹)</td>
                                    <td>{data.totalAmount}</td>
                                </tr>
                                <tr>
                                    <td>Discount Percentage (%)</td>
                                    <td>{data.discount} %</td>
                                </tr>
                                <tr>
                                    <td>Tax (₹)</td>
                                    <td>{data.tax}</td>
                                </tr>
                                <tr>
                                    <td>Net Amount (₹)</td>
                                    <td className="text-primary">{data.netAmount}</td>
                                </tr>
                                <tr>
                                    <td>Paid Amount (₹)</td>
                                    <td>{data.paymentAmount}</td>
                                </tr>
                                <tr>
                                    <td>Due Amount (₹)</td>
                                    <td>{data.balanceAmount}</td>
                                </tr>
                            </tbody>
                        </Table>
                    </div>
          
            </Col>
            <hr />
        </Row>

    );
};

export default PaymentDetails;
